# Generated by Django 5.1.4 on 2026-03-12 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('investments', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('stocks', 'Ações'), ('fii', 'FIIs'), ('fixed_prefixed', 'Renda Fixa Pré-Fixada'), ('fixed_postfixed', 'Renda Fixa Pós-Fixada'), ('treasury', 'Tesouro Direto'), ('crypto', 'Criptomoedas'), ('pension', 'Previdência Privada'), ('savings', 'Poupança'), ('etf', 'ETF'), ('bdr', 'BDR'), ('other', 'Outro')], max_length=20, unique=True)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('icon', models.CharField(default='trending-up', max_length=50)),
                ('liquidity_days', models.IntegerField(default=0, help_text='D+0, D+1, etc.')),
                ('is_taxable', models.BooleanField(default=True)),
                ('ir_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Classe de Ativo',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-current_value'], 'verbose_name': 'Investimento', 'verbose_name_plural': 'Investimentos'},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
        migrations.AddField(
            model_name='investment',
            name='average_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Preço médio'),
        ),
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Preço atual'),
        ),
        migrations.AddField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='daily_change',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='daily_change_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='investment',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='investment',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor aplicado'),
        ),
        migrations.AddField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
        migrations.AddField(
            model_name='investment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='ownership',
            field=models.CharField(choices=[('personal', 'Pessoal'), ('shared', 'Compartilhado')], default='personal', max_length=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='investment',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('prefixed', 'Pré-fixado % a.a.'), ('cdi', '% do CDI'), ('ipca', 'IPCA + % a.a.'), ('selic', 'Selic'), ('other', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='rate_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Taxa (%)'),
        ),
        migrations.AddField(
            model_name='investment',
            name='ticker',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Ticker'),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_dividends',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='investment',
            name='asset_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.assetclass'),
        ),
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target_date', models.DateField()),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.assetclass')),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goals', to='core.familygroup')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='investments.investment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Investimento',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda'), ('dividend', 'Dividendo'), ('jcp', 'JCP'), ('income', 'Rendimento'), ('split', 'Desdobramento'), ('grouping', 'Grupamento')], max_length=10)),
                ('date', models.DateField(verbose_name='Data')),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='Quantidade')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Preço unitário')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor total')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxas')),
                ('ir_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IR retido')),
                ('broker', models.CharField(blank=True, max_length=100, verbose_name='Corretora')),
                ('notes', models.TextField(blank=True)),
                ('financial_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions', to='transactions.transaction')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Transação de Investimento',
                'ordering': ['-date'],
            },
        ),
    ]
