# Generated by Django 5.1.4 on 2026-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('personal', 'Pessoal'), ('shared', 'Compartilhada')], default='personal', max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da conta')),
                ('account_type', models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Poupança'), ('wallet', 'Carteira/Espécie'), ('digital', 'Conta Digital'), ('investment', 'Conta Investimento'), ('salary', 'Conta Salário')], max_length=15, verbose_name='Tipo')),
                ('bank', models.CharField(choices=[('nubank', 'Nubank'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa'), ('inter', 'Inter'), ('xp', 'XP Investimentos'), ('btg', 'BTG Pactual'), ('c6', 'C6 Bank'), ('picpay', 'PicPay'), ('other', 'Outro')], default='other', max_length=15)),
                ('bank_custom', models.CharField(blank=True, max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo inicial')),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('icon', models.CharField(default='wallet', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_total', models.BooleanField(default=True, verbose_name='Incluir no total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method_type', models.CharField(choices=[('pix', 'PIX'), ('ted', 'TED/DOC'), ('boleto', 'Boleto'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('credit', 'Cartão de Crédito'), ('other', 'Outro')], max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
            },
        ),
    ]
