# Generated by Django 5.1.4 on 2026-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10)),
                ('icon', models.CharField(default='tag', max_length=50)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'ordering': ['name'],
            },
        ),
    ]
