# Generated by Django 5.1.4 on 2026-06-26 19:15

import apps.integrations.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('cards', '0003_cardinvoice_payment_transaction'),
        ('core', '0002_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluggyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluggy_item_id', models.CharField(max_length=64, unique=True)),
                ('connector_id', models.IntegerField(blank=True, null=True)),
                ('connector_name', models.CharField(blank=True, max_length=120)),
                ('connector_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('updating', 'Atualizando'), ('updated', 'Atualizado'), ('login_error', 'Erro de login'), ('outdated', 'Desatualizado'), ('waiting_user_input', 'Aguardando usuário'), ('error', 'Erro')], default='pending', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluggy_items', to='core.familygroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluggy_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão Pluggy',
                'verbose_name_plural': 'Conexões Pluggy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluggyAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluggy_account_id', models.CharField(max_length=64, unique=True)),
                ('pluggy_type', models.CharField(choices=[('BANK', 'Conta bancária'), ('CREDIT', 'Cartão de crédito')], default='BANK', max_length=10)),
                ('pluggy_subtype', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('number_masked', apps.integrations.fields.EncryptedTextField(blank=True, default='')),
                ('pluggy_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_code', models.CharField(default='BRL', max_length=3)),
                ('link_mode', models.CharField(choices=[('pending', 'Aguardando decisão'), ('created', 'Conta criada'), ('mapped', 'Vinculada a conta existente'), ('ignored', 'Ignorada')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluggy_links', to='cards.creditcard')),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluggy_links', to='accounts.financialaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='integrations.pluggyitem')),
            ],
            options={
                'verbose_name': 'Vínculo de conta Pluggy',
                'verbose_name_plural': 'Vínculos de conta Pluggy',
                'ordering': ['name'],
            },
        ),
    ]
