# Generated by Django 5.1.4 on 2026-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluggyitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('updating', 'Atualizando'), ('updated', 'Atualizado'), ('partial_success', 'Sucesso parcial'), ('login_error', 'Erro de login'), ('outdated', 'Desatualizado'), ('waiting_user_input', 'Aguardando usuário'), ('error', 'Erro')], default='pending', max_length=24),
        ),
    ]
