# Generated by Django 5.1.4 on 2026-06-26 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('cards', '0003_cardinvoice_payment_transaction'),
        ('categories', '0002_initial'),
        ('core', '0002_securityevent'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pluggy', 'Open Finance (Pluggy)')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_auto_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('family_group', 'external_source', 'external_id'), name='uniq_external_txn'),
        ),
    ]
