# Generated by Django 5.1.4 on 2026-03-12 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_month', models.DateField()),
                ('closing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('future', 'Futura'), ('open', 'Aberta'), ('closed', 'Fechada'), ('paid', 'Paga'), ('partial', 'Pago Parcial'), ('overdue', 'Vencida')], default='open', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fatura',
                'ordering': ['-reference_month'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(choices=[('personal', 'Pessoal'), ('shared', 'Compartilhado')], default='personal', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('other', 'Outro')], max_length=15)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('holder_name', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_day', models.IntegerField()),
                ('due_day', models.IntegerField()),
                ('color_from', models.CharField(default='#7c3aed', max_length=7)),
                ('color_to', models.CharField(default='#3b82f6', max_length=7)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_cards', to='accounts.financialaccount')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
            },
        ),
    ]
