# Generated by Django 5.1.4 on 2026-03-12 20:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('budgets', '0002_initial'),
        ('categories', '0002_initial'),
        ('core', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-reference_month', 'category__name'], 'verbose_name': 'Orçamento'},
        ),
        migrations.AddField(
            model_name='budget',
            name='alert_threshold',
            field=models.IntegerField(default=80, verbose_name='Alertar em %'),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='reference_month',
            field=models.DateField(default=datetime.date.today, verbose_name='Mês de referência'),
        ),
        migrations.AddField(
            model_name='budget',
            name='rollover',
            field=models.BooleanField(default=False, verbose_name='Acumular saldo'),
        ),
        migrations.AddField(
            model_name='budget',
            name='scope',
            field=models.CharField(choices=[('personal', 'Pessoal'), ('family', 'Familiar')], default='personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Limite'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('owner', 'category', 'reference_month', 'scope')},
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da meta')),
                ('goal_type', models.CharField(choices=[('savings', 'Reserva/Poupança'), ('debt_payoff', 'Quitar Dívida'), ('purchase', 'Compra Planejada'), ('emergency', 'Fundo de Emergência'), ('investment', 'Meta de Investimento'), ('travel', 'Viagem')], max_length=15)),
                ('scope', models.CharField(choices=[('personal', 'Pessoal'), ('family', 'Familiar')], default='personal', max_length=10)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor atual')),
                ('target_date', models.DateField(verbose_name='Data alvo')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('icon', models.CharField(default='target', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.familygroup')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='accounts.financialaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='budgets.financialgoal')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
