#!/bin/sh
set -eu

POSTGRES_HOST="${POSTGRES_HOST:-db}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
PGBOUNCER_MAX_CLIENT_CONN="${PGBOUNCER_MAX_CLIENT_CONN:-200}"
PGBOUNCER_DEFAULT_POOL_SIZE="${PGBOUNCER_DEFAULT_POOL_SIZE:-20}"
PGBOUNCER_RESERVE_POOL_SIZE="${PGBOUNCER_RESERVE_POOL_SIZE:-5}"
PGBOUNCER_USER="${PGBOUNCER_USER:-${POSTGRES_USER:-}}"
PGBOUNCER_PASSWORD="${PGBOUNCER_PASSWORD:-${POSTGRES_PASSWORD:-}}"

if [ -z "${POSTGRES_DB:-}" ] || [ -z "${POSTGRES_USER:-}" ] || [ -z "${POSTGRES_PASSWORD:-}" ]; then
    echo "POSTGRES_DB, POSTGRES_USER and POSTGRES_PASSWORD are required" >&2
    exit 1
fi

if [ -z "$PGBOUNCER_USER" ] || [ -z "$PGBOUNCER_PASSWORD" ]; then
    echo "PGBOUNCER_USER and PGBOUNCER_PASSWORD are required" >&2
    exit 1
fi

export POSTGRES_HOST POSTGRES_PORT POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD
export PGBOUNCER_USER PGBOUNCER_MAX_CLIENT_CONN PGBOUNCER_DEFAULT_POOL_SIZE PGBOUNCER_RESERVE_POOL_SIZE

envsubst < /etc/pgbouncer/pgbouncer.ini.template > /run/pgbouncer/pgbouncer.ini
printf '"%s" "%s"\n' "$PGBOUNCER_USER" "$PGBOUNCER_PASSWORD" > /run/pgbouncer/userlist.txt

exec pgbouncer /run/pgbouncer/pgbouncer.ini
