# Generated by Django 5.1.4 on 2026-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('budget', 'Orçamento'), ('bill', 'Fatura'), ('balance', 'Saldo'), ('goal', 'Meta'), ('portfolio', 'Carteira'), ('recurring', 'Recorrente'), ('info', 'Informação')], default='info', max_length=20),
        ),
    ]
